const reviews = [
    {
      id: 1,
      fullName: 'John Doe',
      residence: 'New York, USA',
      rating: 4,
      content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      likes: 10,
      datePosted: new Date(2023, 4, 15),
    },
    {
      id: 2,
      fullName: 'Jane Smith',
      residence: 'London, UK',
      rating: 5,
      content: 'Nulla facilisi. Proin sollicitudin, orci et pharetra aliquam.',
      likes: 15,
      datePosted: new Date(2023, 4, 20),
    },
    {
      id: 3,
      fullName: 'Mark Johnson',
      residence: 'San Francisco, USA',
      rating: 3,
      content: 'Suspendisse sed condimentum mauris, sit amet laoreet nulla.',
      likes: 5,
      datePosted: new Date(2023, 4, 25),
    },
    {
      id: 4,
      fullName: 'Emma Davis',
      residence: 'Sydney, Australia',
      rating: 5,
      content: 'Vestibulum auctor, erat vitae iaculis congue, mauris erat.',
      likes: 12,
      datePosted: new Date(2023, 4, 28),
    },
    {
      id: 5,
      fullName: 'Michael Brown',
      residence: 'Toronto, Canada',
      rating: 4,
      content: 'Fusce vel leo nec tortor ullamcorper tempor.',
      likes: 8,
      datePosted: new Date(2023, 5, 1),
    },
    {
      id: 6,
      fullName: 'Sarah Lee',
      residence: 'Seoul, South Korea',
      rating: 5,
      content: 'Curabitur eleifend leo sit amet congue dapibus.',
      likes: 20,
      datePosted: new Date(2023, 5, 5),
    },
    {
      id: 7,
      fullName: 'David Wilson',
      residence: 'Berlin, Germany',
      rating: 2,
      content: 'Donec volutpat purus nec augue lobortis elementum.',
      likes: 3,
      datePosted: new Date(2023, 5, 10),
    },
    {
      id: 8,
      fullName: 'Sophia Martinez',
      residence: 'Mexico City, Mexico',
      rating: 4,
      content: 'Quisque iaculis leo eget erat varius fringilla.',
      likes: 9,
      datePosted: new Date(2023, 5, 15),
    },
    {
      id: 9,
      fullName: 'Ryan Wilson',
      residence: 'Melbourne, Australia',
      rating: 3,
      content: 'Etiam convallis lorem nec mauris scelerisque placerat.',
      likes: 7,
      datePosted: new Date(2023, 5, 20),
    },
    {
      id: 10,
      fullName: 'Olivia Anderson',
      residence: 'Paris, France',
      rating: 5,
      content: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices.',
      likes: 18,
      datePosted: new Date(2023, 5, 25),
    },
    
    
  ];

  export default reviews;